### ISSUE TITLE
add new models

### ISSUE THREAD

**Issue by kriswangchunyan** [MarkusHuang/YOLOv8-DeepSort-PyQt-GUI#3]
hello,how to add the new models in the YOLOV8 GUI? thank you

**Comment by jingh-ai** [comment]
The models in this project were trained on the COCO dataset. All models are saved in folder weights/ by tasks and sizes, the txt file contains class names is also saved in it. You can replace these with your own model and class names file, and it is better to disable the model selection and task selection in the GUI.
